config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'thanks' =>'pages#thanks'
  resources :signups

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def thanks
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @signup = Signup.new
  end
  def create
    @signup = Signup.new(signup_params)
    
    if @signup.save
      redirect_to '/thanks'
    end
  end
  private
  def signup_params
    params.require(:signup).permit(:firstname, :email)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 
  <%= csrf_meta_tags %>
</head>
<body>
<div class="menu">
  <ul>
    <li><%=link_to "Home", home_path%></li> 
    <li><%=link_to "About", about_path%></li>
    <li><%=link_to "Contact", new_signup_path%></li>
  </ul>
  <img alt="Close" class="icon-close" src="https://www.dropbox.com/s/eojylwf0p2stehg/vlcsnap-2015-04-08-01h44m44s184.png?dl=1" width="24px" /> </div>
<%= yield %>
  <div class="footer">
    <div class="container">
      <p>A Shutterbugg Project</p> 
    </div> 
  </div>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
</body>
</html>

app/views/pages/about.html.erb
 <div class="about-main">
   <img alt="Open" class="icon-menu" src="https://www.dropbox.com/s/iyumagblldmsbbw/vlcsnap-2015-04-04-18h19m28s3.png?dl=1"> 
   <h1>Relive your favorite memories</h1>
</div>
<div class="about-supporting"> 
  <div class="container"> 
    <h2>No more sorting through photos</h2> <p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p> 
    <li><%=link_to "Sign up", new_signup_path%></li>
  </div>
</div>

app/views/pages/home.html.erb
 <div class="home-main"> 
   <img alt="Open" class="icon-menu" src="https://www.dropbox.com/s/g6o53hybiupob4h/vlcsnap-2015-10-01-22h28m09s102.png?dl=1" width="24px" /> 
   <div class="container"> 
     <div class="row">
       <div class="content col-md-6 col-md-offset-6">
         <h1>Create and share Stories</h1> 
         <p class="btn btn-primary"><%=link_to "Learn more", about_path%></p> 
       </div> 
     </div>
   </div> 
</div> 
<div class="home-supporting">
  <div class="container">
    <h2>Relive and share your adventures</h2>
    <p>Stories automatically creates a digital journal with your best photos.</p>
  </div> 
</div>
<div class="home-secondary">
  <div class="container"> </div>
</div> 
<div class="home-about">
  <div class="container"> 
    <h2>Discover Stories</h2> 
    <p class="btn btn-primary"><%=link_to "Learn more", about_path%></p>
  </div> 
</div>

app/views/pages/thanks.html.erb
 <div class="contact-main">
   <img alt="Open" class="icon-menu" 
    src="https://www.dropbox.com/s/5cpju7xed5rynoz/vlcsnap-2015-04-06-23h28m14s92.png?dl=1" width="24px" /> <div class="content container"> <h1>Thanks. We'll be in touch.</h1> </div> </div> 

app/views/signups/new.html.erb
<div class="contact-main"> 
  <img alt="Open" class="icon-menu" src="https://www.dropbox.com/s/g6o53hybiupob4h/vlcsnap-2015-10-01-22h28m09s102.png?dl=1" width="24px" />
  <div class="content container"> 
    <h1>Get the latest updates from Stories</h1>
    <div class="row"> 
      <div class="col-md-4 col-md-4-offset"></div> <div class="col-md-4"> 
        
 <%= form_for(@signup) do |f| %>
    <div class="field">
      <%= f.label :FirstName%>
      <%= f.text_field :firstname%>
      <br><br>
      <%= f.label :Email%>
      <%= f.text_field :email%>
    </div>
    <div class="actions">
      <%= f.submit "Join" %>
    </div>
    <%end%>
      
      </div> 
    </div>
    <div class="col-md-4 col-md-4-offset"></div> 
  </div> 
</div>